CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO card (card_id, card_name, card_number, card_image_url, card_forward, card_reverse)
        VALUES
            (uuid_generate_v4(), 'The Fool', 1, 'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg', 'The Fool card represents new beginnings, innocence, and a leap of faith. It signifies embarking on a journey with an open heart and a sense of adventure. This card encourages you to trust in the universe and embrace the unknown.', 'The reverse of The Fool card may indicate recklessness, naivety, or missed opportunities. It may suggest a need to be more cautious and grounded in your approach to life.'),
            (uuid_generate_v4(), 'The Magician', 2, 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg', 'The Magician card represents manifestation, resourcefulness, and power. It signifies the ability to harness your skills and talents to achieve your goals. This card encourages you to take action and make things happen through focused intention and willpower.', 'The reverse of The Magician card may indicate manipulation, untapped potential, or misuse of power. It may suggest a need to be mindful of your actions and their consequences.'),
            (uuid_generate_v4(), 'The High Priestess', 3, 'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg', 'The High Priestess card represents intuition, mystery, and inner wisdom. It signifies a deep connection to the subconscious mind and the mysteries of the universe. This card encourages you to listen to your inner voice and trust your instincts.', 'The reverse of The High Priestess card may indicate hidden agendas, secrets, or deception. It may suggest a need to look beneath the surface and uncover the truth in a situation.'),
            (uuid_generate_v4(), 'The Empress', 4, 'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg', 'The Empress card represents fertility, nurturing, and abundance. It signifies the creation of new life and the nurturing of ideas and projects. This card encourages you to embrace your feminine energy and connect with the nurturing aspects of yourself and others.', 'The reverse of The Empress card may indicate infertility, neglect, or dependence. It may suggest a need to nurture yourself and others more effectively and find balance in your relationships.'),
            (uuid_generate_v4(), 'The Emperor', 5, 'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg', 'The Emperor card represents authority, stability, and leadership. It signifies the establishment of order and structure in your life. This card encourages you to take control of your circumstances and assert your authority with confidence and integrity.', 'The reverse of The Emperor card may indicate tyranny, control issues, or lack of direction. It may suggest a need to be more flexible and open to the ideas and perspectives of others.'),
            (uuid_generate_v4(), 'The Hierophant', 6, 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg', 'The Hierophant card represents tradition, conformity, and spiritual guidance. It signifies adherence to established beliefs and seeking wisdom from spiritual mentors. This card encourages you to honor tradition and seek guidance from trusted sources.', 'The reverse of The Hierophant card may indicate rebellion, nonconformity, or spiritual disillusionment. It may suggest a need to question traditional beliefs and find your own path to spiritual fulfillment.'),
            (uuid_generate_v4(), 'The Lovers', 7, 'https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg', 'The Lovers card represents love, harmony, and relationships. It signifies deep emotional connections and the union of opposites. This card encourages you to follow your heart and make choices that align with your values and desires.', 'The reverse of The Lovers card may indicate disharmony, imbalance, or difficult choices. It may suggest a need to reevaluate your relationships and make decisions that are in alignment with your highest good.'),
            (uuid_generate_v4(), 'The Chariot', 8, 'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg', 'The Chariot card represents determination, willpower, and victory. It signifies overcoming obstacles and achieving success through sheer determination and perseverance. This card encourages you to stay focused on your goals and maintain control over your emotions and actions.', 'The reverse of The Chariot card may indicate lack of direction, self-doubt, or obstacles blocking your path. It may suggest a need to reassess your goals and take a more strategic approach to achieving them.'),
            (uuid_generate_v4(), 'Strength', 9, 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg', 'The Strength card represents courage, inner strength, and resilience. It signifies the ability to overcome challenges with grace and compassion. This card encourages you to tap into your inner reserves of strength and face difficulties with confidence and determination.', 'The reverse of the Strength card may indicate self-doubt, weakness, or lack of confidence. It may suggest a need to believe in yourself more and trust in your abilities to overcome obstacles.');

INSERT INTO gametype (game_type_id, game_type_all_card_num, game_type_select_card_num, game_type_fan_card_num, game_type_name)
    VALUES
        (uuid_generate_v4(), 52, 3, 1, 'love'),
        (uuid_generate_v4(), 52, 3, 1, 'health'),
        (uuid_generate_v4(), 52, 3, 1, 'fortune');


INSERT INTO game (game_id, game_type_id, game_select_card_id, game_all_select_card_id, game_quest, game_started_at, game_finished_at)
    VALUES
        (uuid_generate_v4(), (SELECT game_type_id FROM gametype LIMIT 1), (SELECT card_id FROM card LIMIT 1), (SELECT card_id FROM card LIMIT 1), '질문 1', '2024-04-28 12:00:00', '2024-04-28 13:00:00'),
        (uuid_generate_v4(), (SELECT game_type_id FROM gametype LIMIT 1), (SELECT card_id FROM card LIMIT 1), (SELECT card_id FROM card LIMIT 1), '질문 2', '2024-04-28 12:00:00', '2024-04-28 13:00:00'),
        (uuid_generate_v4(), (SELECT game_type_id FROM gametype LIMIT 1), (SELECT card_id FROM card LIMIT 1), (SELECT card_id FROM card LIMIT 1), '질문 3', '2024-04-28 12:00:00', '2024-04-28 13:00:00');