# Generated by Django 5.0.3 on 2024-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("card_id", models.UUIDField(primary_key=True, serialize=False)),
                ("card_name", models.TextField(unique=True)),
                ("card_number", models.IntegerField(unique=True)),
                ("card_image_url", models.TextField(unique=True)),
            ],
            options={
                "db_table": "card",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cardcontents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forward", models.TextField(blank=True, null=True)),
                ("reverse", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "cardcontents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.UUIDField(primary_key=True, serialize=False)),
                ("game_type_id", models.IntegerField(unique=True)),
                ("select_card_id", models.IntegerField(unique=True)),
                ("all_select_card_id", models.IntegerField()),
            ],
            options={
                "db_table": "game",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Gamequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_quest", models.TextField(unique=True)),
            ],
            options={
                "db_table": "gamequest",
                "managed": False,
            },
        ),
    ]
